version: '3.4'

services:
  test:
    image: ${DOCKER_REGISTRY-}test
    build:
      context: .
      dockerfile: TEST\Dockerfile
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 123qwe
      PGDATA: /data/postgres
      POSTGRES_DB: testdb
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
networks:
  db:
    driver: bridge

volumes:
  db:
