version: '3.8'

services:
  db:
    container_name: postgres
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 123qwe
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: testdb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5332:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d testdb"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - backend

  test:
    image: ${DOCKER_REGISTRY-}test
    build:
      context: .
      dockerfile: TEST/Dockerfile
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=testdb;Username=test;Password=123qwe
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  db_data:
